# Generated by Django 4.1.3 on 2024-01-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('date_of_entry', models.DateField(verbose_name='Дата ввода в эксплуатацию')),
                ('base_fuel_consumption', models.FloatField(verbose_name='Базовый расход топлива')),
                ('trailer_fuel_consumption', models.FloatField(verbose_name='Расход топлива на прицеп')),
                ('transport_fuel_consumption', models.FloatField(verbose_name='Расход топлива - транспортная работа')),
                ('initial_mileage', models.IntegerField(verbose_name='Начальный пробег')),
                ('is_used', models.BooleanField(verbose_name='Используется?')),
                ('fuel_type', models.CharField(max_length=50, verbose_name='Тип топлива')),
                ('registration_number', models.CharField(max_length=20, verbose_name='Регистрационный номер')),
                ('depreciation', models.FloatField(verbose_name='Амортизационные отчисления')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(verbose_name='Дата создания')),
                ('insurance_costs', models.FloatField(verbose_name='Затраты на страхование')),
                ('expected_revenue', models.FloatField(verbose_name='Ожидаемая выручка')),
                ('other_costs', models.FloatField(verbose_name='Прочие затраты')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата завершения')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('driver1', models.CharField(max_length=100, verbose_name='Водитель 1')),
                ('driver2', models.CharField(max_length=100, verbose_name='Водитель 2')),
                ('climate_control', models.BooleanField(verbose_name='Климат-контроль')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='RouteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=100, verbose_name='Пункт')),
                ('loading_unloading', models.CharField(max_length=50, verbose_name='Погрузка/Выгрузка')),
                ('arrival_date_time', models.DateTimeField(verbose_name='Дата и время прибытия')),
                ('cargo_weight', models.FloatField(verbose_name='Масса груза')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Детали маршрута заявки',
                'verbose_name_plural': 'Детали маршрутов заявок',
            },
        ),
        migrations.CreateModel(
            name='RequestCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_choice', models.CharField(max_length=10, verbose_name='Выбор значения')),
                ('fuel_consumption', models.FloatField(verbose_name='Расход топлива')),
                ('driver1_payment', models.FloatField(verbose_name='Оплата водителю 1')),
                ('driver2_payment', models.FloatField(verbose_name='Оплата водителю 2')),
                ('depreciation', models.FloatField(verbose_name='Амортизация')),
                ('insurance', models.FloatField(verbose_name='Страхование')),
                ('other_costs', models.FloatField(verbose_name='Прочие затраты')),
                ('total', models.FloatField(verbose_name='Итого')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Себестоимость заявки',
                'verbose_name_plural': 'Себестоимости заявок',
            },
        ),
    ]
